// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TallerEF_Aguilera_Martinez.Models;

#nullable disable

namespace TallerEF_Aguilera_Martinez.Migrations
{
    [DbContext(typeof(EstudianteContext))]
    partial class EstudianteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TallerEF_Aguilera_Martinez.Models.Calificaciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<float>("EXA_P1")
                        .HasColumnType("real");

                    b.Property<float>("EXA_P2")
                        .HasColumnType("real");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("EstudiantesPorParaleloId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<float>("GF_P1")
                        .HasColumnType("real");

                    b.Property<float>("GF_P2")
                        .HasColumnType("real");

                    b.Property<float>("GP_P1")
                        .HasColumnType("real");

                    b.Property<float>("GP_P2")
                        .HasColumnType("real");

                    b.Property<int>("IdEstudiantesPorParalelo")
                        .HasColumnType("int");

                    b.Property<float>("PRO_GEN")
                        .HasColumnType("real");

                    b.Property<float>("PRO_P1")
                        .HasColumnType("real");

                    b.Property<float>("PRO_P2")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("EstudiantesPorParaleloId");

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("TallerEF_Aguilera_Martinez.Models.DetalleParalelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdMateria")
                        .HasColumnType("int");

                    b.Property<int>("IdParalelo")
                        .HasColumnType("int");

                    b.Property<int>("IdProfesor")
                        .HasColumnType("int");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<int>("ParaleloId")
                        .HasColumnType("int");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.HasIndex("ParaleloId");

                    b.HasIndex("ProfesorId");

                    b.ToTable("DetallesParalelos");
                });

            modelBuilder.Entity("TallerEF_Aguilera_Martinez.Models.Estudiante", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstudianteId"), 1L, 1);

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstudianteId");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("TallerEF_Aguilera_Martinez.Models.EstudiantesPorParalelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DetalleParaleloId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDetalleParalelo")
                        .HasColumnType("int");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DetalleParaleloId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("EstudiantesPorParalelos");
                });

            modelBuilder.Entity("TallerEF_Aguilera_Martinez.Models.Materia", b =>
                {
                    b.Property<int>("MateriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MateriaId"), 1L, 1);

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("semestre")
                        .HasColumnType("int");

                    b.HasKey("MateriaId");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("TallerEF_Aguilera_Martinez.Models.Paralelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jornada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Paralelos");
                });

            modelBuilder.Entity("TallerEF_Aguilera_Martinez.Models.Profesor", b =>
                {
                    b.Property<int>("ProfesorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfesorId"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfesorId");

                    b.ToTable("Profesores");
                });

            modelBuilder.Entity("TallerEF_Aguilera_Martinez.Models.ProfesorPorMateria", b =>
                {
                    b.Property<int>("ProfesorPorMateriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfesorPorMateriaId"), 1L, 1);

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.HasKey("ProfesorPorMateriaId");

                    b.HasIndex("MateriaId");

                    b.HasIndex("ProfesorId");

                    b.ToTable("ProfesoresPorMaterias");
                });

            modelBuilder.Entity("TallerEF_Aguilera_Martinez.Models.Calificaciones", b =>
                {
                    b.HasOne("TallerEF_Aguilera_Martinez.Models.EstudiantesPorParalelo", "EstudiantesPorParalelo")
                        .WithMany("Calificaciones")
                        .HasForeignKey("EstudiantesPorParaleloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstudiantesPorParalelo");
                });

            modelBuilder.Entity("TallerEF_Aguilera_Martinez.Models.DetalleParalelo", b =>
                {
                    b.HasOne("TallerEF_Aguilera_Martinez.Models.Materia", "Materia")
                        .WithMany("DetallesParalelos")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TallerEF_Aguilera_Martinez.Models.Paralelo", "Paralelo")
                        .WithMany("DetallesParalelos")
                        .HasForeignKey("ParaleloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TallerEF_Aguilera_Martinez.Models.Profesor", "Profesor")
                        .WithMany("DetallesParalelos")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("Paralelo");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("TallerEF_Aguilera_Martinez.Models.EstudiantesPorParalelo", b =>
                {
                    b.HasOne("TallerEF_Aguilera_Martinez.Models.DetalleParalelo", "DetalleParalelo")
                        .WithMany("EstudiantesPorParalelos")
                        .HasForeignKey("DetalleParaleloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TallerEF_Aguilera_Martinez.Models.Estudiante", "Estudiante")
                        .WithMany("EstudiantesPorParalelos")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetalleParalelo");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("TallerEF_Aguilera_Martinez.Models.ProfesorPorMateria", b =>
                {
                    b.HasOne("TallerEF_Aguilera_Martinez.Models.Materia", "Materia")
                        .WithMany("ProfesorPorMateria")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TallerEF_Aguilera_Martinez.Models.Profesor", "Profesor")
                        .WithMany("ProfesorPorMateria")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("TallerEF_Aguilera_Martinez.Models.DetalleParalelo", b =>
                {
                    b.Navigation("EstudiantesPorParalelos");
                });

            modelBuilder.Entity("TallerEF_Aguilera_Martinez.Models.Estudiante", b =>
                {
                    b.Navigation("EstudiantesPorParalelos");
                });

            modelBuilder.Entity("TallerEF_Aguilera_Martinez.Models.EstudiantesPorParalelo", b =>
                {
                    b.Navigation("Calificaciones");
                });

            modelBuilder.Entity("TallerEF_Aguilera_Martinez.Models.Materia", b =>
                {
                    b.Navigation("DetallesParalelos");

                    b.Navigation("ProfesorPorMateria");
                });

            modelBuilder.Entity("TallerEF_Aguilera_Martinez.Models.Paralelo", b =>
                {
                    b.Navigation("DetallesParalelos");
                });

            modelBuilder.Entity("TallerEF_Aguilera_Martinez.Models.Profesor", b =>
                {
                    b.Navigation("DetallesParalelos");

                    b.Navigation("ProfesorPorMateria");
                });
#pragma warning restore 612, 618
        }
    }
}
